# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/cudf/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/raft/labels

Python:
 - python/**
 - notebooks/**

libraft:
 - cpp/**

CMake:
 - **/CMakeLists.txt
 - **/cmake/**

Java:
 - java/**

Ops:
 - .github/**
 - /ci/**
 - conda/**
 - **/Dockerfile
 - **/.dockerignore
 - docker/**
